# Generated by Django 5.0.4 on 2024-04-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_user_managers_category_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='lastname',
        ),
    ]
