# Generated by Django 5.0.4 on 2024-04-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_userdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.userdetails'),
        ),
    ]
