# Generated by Django 5.0.4 on 2024-04-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='images_colors',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='videos',
        ),
        migrations.AddField(
            model_name='productimagescolors',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
