# Generated by Django 5.0.4 on 2024-04-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_productinfo_images_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='manufactory',
            new_name='manufacture',
        ),
    ]
