# Generated by Django 5.0.4 on 2024-04-10 08:07

import cloudinary.models
import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_productimagescolors_url_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='percent_sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsell',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productsell',
            name='sold_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='url_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[ecommerce.models.validate_video_size]),
        ),
    ]
