# Generated by Django 5.0.4 on 2024-04-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_productsell_insurrance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condition',
            new_name='VoucherCondition',
        ),
    ]
