# Generated by Django 5.0.4 on 2024-04-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_rename_condition_vouchercondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='condition',
        ),
        migrations.AddField(
            model_name='vouchercondition',
            name='voucher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.voucher'),
        ),
        migrations.AlterField(
            model_name='vouchercondition',
            name='order_fee_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchercondition',
            name='voucher_sale_max',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='User_Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.voucher')),
            ],
        ),
    ]
