# Generated by Django 5.0.4 on 2024-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_voucher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercondition',
            name='voucher_sale',
            field=models.FloatField(default=0),
        ),
    ]
