# Generated by Django 5.0.4 on 2024-04-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_vouchercondition_voucher_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='all_time_used',
            new_name='maximum_time_used',
        ),
    ]
