# Generated by Django 5.0.4 on 2024-04-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_rename_all_time_used_voucher_maximum_time_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchertype',
            name='voucher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.voucher'),
        ),
    ]
