# Generated by Django 5.0.4 on 2024-04-10 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_vouchertype_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchertype',
            name='voucher',
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.vouchertype'),
        ),
    ]
