# Generated by Django 5.0.4 on 2024-04-11 03:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_statusconfirmationshop_confirmationshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationshop',
            name='note',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
