# Generated by Django 5.0.4 on 2024-04-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_confirmationshop_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusconfirmationshop',
            old_name='status',
            new_name='status_content',
        ),
        migrations.AlterField(
            model_name='confirmationshop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.statusconfirmationshop'),
        ),
    ]
