"""
Django settings for eCommerceApp project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import cloudinary
import pymysql

pymysql.install_as_MySQLdb()

cloudinary.config(
    cloud_name="diwxda8bi",
    api_key="358748635141677",
    api_secret="QBGsplvCUjvxqZFWkpQBWKFT91I"
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = '%s/ecommerce/static/' % BASE_DIR

CKEDITOR_UPLOAD_PATH = "ckeditors/images/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qf)xyu3+q#a9=wx8m=r(Y(HDHU(D(DA))&tm^nh_%%7@9#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTHENTICATION_BACKENDS = [  # For Oauth2
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ecommerce',
    'rest_framework',
    'ckeditor',
    'ckeditor_uploader',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
    # 'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'django_extensions',

]

# SITE_ID = 1

LOGIN_REDIRECT_URL = '/accounts/profile/'  # Redirect user logged in
LOGOUT_REDIRECT_URL = '/accounts/logout/'  # Redirect user logged out
SOCIALACCOUNT_LOGIN_ON_GET = True  # Skip allauth middle page login
SOCIALACCOUNT_AUTO_SIGNUP = True  # Skip allauth middle page signup

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'APP': {
            'client_id': '1129130478229280',
            # '': '16e7225bb8abb238614204164a7a1d30',
            'key': ''
        },
        'METHOD': 'oauth2',  # Set to 'js_sdk' to use the Facebook connect SDK
        # 'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        # 'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
    },
    'github': {
        'APP': {
            'client_id': 'c750e15daeaa022800e5',
            # '': 'ff00049a97d9ef41bc3354f8e00f135f4ab166db',
            'key': ''
        },
        'SCOPE': [
            'user',
            'repo',
            'read:org',
        ],
    },
    'google': {
        'APP': {
            'client_id': '718959889156-agldhitsii4bvi9iue3atjub0kf5mjfs.apps.googleusercontent.com',
            # '': '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',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',  # get refresh token, access token even though the user is offline
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# SOCIAL_AUTH_FACEBOOK_KEY = '1129130478229280'
# SOCIAL_AUTH_FACEBOOK_SECRET = '16e7225bb8abb238614204164a7a1d30'
# SOCIAL_AUTH_GITHUB_OAUTH2_KEY = 'c750e15daeaa022800e5'
# SOCIAL_AUTH_GITHUB_OAUTH2_SECRET = 'ff00049a97d9ef41bc3354f8e00f135f4ab166db'
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '718959889156-agldhitsii4bvi9iue3atjub0kf5mjfs.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
    # 'logingoogle.middleware.AutoLogoutMiddleware',

]

ROOT_URLCONF = 'eCommerceApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eCommerceApp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecommerceapp',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': '',
    }
}

AUTH_USER_MODEL = 'ecommerce.User'  # khai báo lớp User của mình để chứng thực

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CLIENT_ID = 'CdLY1uAK55c1aeqQkidSN6Nuh1EgDIcuecfHdoKH'
# CLIENT_SECRET = 'Y2S3hPPszElGyXvhFn4KrABbDDL4lL5sPdgRd4tPKYRooYzil6qyTdsuunwbJFQtdb0Yal1dxnD0KRCj8JoDdDjlnMN31DItQddAn1A6gZhnlfbe8qPMBbKjeZGXCNA7'

CLIENT_ID = 'pdKVqpXyodpAHJFCYvGG1rO2TMzY8QqWGIn5TADA'
CLIENT_SECRET = 'TTVwfLKnTHn71tww1tkJK3dlns8AVbeiHglPEzvIfqB36OzvVPjuDYVN3bZPioaNJnQcvmoFWaNVjhEUhgreCsRDJ7ISliEAWCYXienSNYIR8pvqliQ8RTYLo5684DAf'
